arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: untranslated_messages.txt
synthetic-package: false
output-class: AppLocalizations
nullable-getter: false
use-deferred-loading: false
